### PR TITLE
feat: enable prettier to keep code formatted in same rulse

### LINKED ISSUE #55: [Dev] `prettier` should be enabled in this project ASAP to keep code formatted in same rulse
image

Hi guys, I think we should employ a code formatter such as [prettier](https://github.com/prettier/prettier) ASAP :)

### PR DESCRIPTION
**Pull request by wj23027**
## Brief Information

Related issues:

- resolve #55 

## Details

- 配置prettier
- 现在运行 `npm run prettier`可以使代码保持相同的格式化。

### CODE REVIEW

**Comment by tyn1998** [comment]
Hi @wj23027, I pulled your code and had a test. More specificly, I ran `npm install` then `npm run prettier`. Then one file was changed:

image

I thought this might be the reason for the error you just mentioned in 229? The error may not be concerned with the quotation but capitalization.

**Comment by wj23027** [comment]
You’re right!After running `npm run prettier`again, the case of the text has changed.

**Comment by wj23027** [comment]
You’re right!After running `npm run prettier`again, the case of the text has changed.

**Comment by tyn1998** [comment]
Just commit and push, I'll approve your PR then :)

**Pull request merged**
